allow:
  header: '*'
  orgins: '*'
auth:
  header: Authorization
aws:
  access_key_id: AKIA27B3VZFOCRX4POER
  s3:
    bucket: albraik-user-image
    endpointUrl: http://albraik-user-image.s3-website-us-east-1.amazonaws.com
  secret_access_key: CR2M3K3O4Fa5ItW1wjcrQ5hRd1TLhxzaraNbjd96
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
img:
  location: D://temp//
mail:
  template:
    admin-register:
      id: 1
    user-register:
      id: 2
reg:
  cor:
    conf: /**
secret:
  key: dofzxhnbsdlzbpajp878ireujgldfkhg0#$%^&*shgh
server:
  port: 8081
  servlet:
    application-display-name: infra
    contextPath: /infra
sign:
  in:
    url: /login/validateUser
  up:
    urls: /register/**
spring:
  application:
    name: infra
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/albraik_db
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
token:
  key: 'myToken '
web:
  jars: webjars/**
